// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB79amW9fIcIACa5xhaMnpO_GXbvk4-SKc',
    appId: '1:475113061000:android:13e823a59b62ac81f77d3d',
    messagingSenderId: '475113061000',
    projectId: 'ai-form-builder-f1d83',
    storageBucket: 'ai-form-builder-f1d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2PPPtVaEXGjBfoH1O7uhRN200ptfZbLk',
    appId: '1:475113061000:ios:3973d156f02be6a7f77d3d',
    messagingSenderId: '475113061000',
    projectId: 'ai-form-builder-f1d83',
    storageBucket: 'ai-form-builder-f1d83.firebasestorage.app',
    androidClientId: '475113061000-bat9069b1bsmb2cm71gtlm77aglgckft.apps.googleusercontent.com',
    iosClientId: '475113061000-kjhje4ur64h0ejllmp63v7akntul2f00.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiformbuilder',
  );

}